spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashion_log
    username: root
    password: 'projectpassword'
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080